simulazione:
  duration: 10000   # durata della simulazione in secondi
  SImax: 4 # numero massimo di job correntemente in esecuzione in un server prima di far scattare la scalabilità verticale (scale up)
  SImin: 2 # numero minimo di job correntemente in esecuzione in un server prima di far scattare la scalabilità verticale (scale down)
  R0max: 0.6 # media del tempo di risposta per job in un server prima di far scattare la scalabilità orizzontale (scale in)
  R0min: 0.4 # media del tempo di risposta per job in un server prima di far scattare la scalabilità orizzontale (scale out)
  slidingWindowSize: 10 # dimensione della finestra mobile per il calcolo della media del tempo di risposta
  horizontalScalingCoolDown: 10 # ritardo fra una scalata orizzontale ed un altra in secondi
  initialServerCount: 1 # numero di server iniziali SENZA CONTARE LO SPIKE SERVER
  cpuMultiplierSpike: 2 # moltiplicatore della CPU per il server spike
  cpuPercentageSpike: 0.4 # percentuale di CPU assegnata alla applicazione del server spike
  schedulingPolicy: "round_robin"   # valori possibili: least_load, round_robin
  fileCsv: "results.csv" # nome del file CSV per i risultati