simulazione:
  duration: 126144000   # durata della simulazione in secondi
  SImax: 4 # numero massimo di job correntemente in esecuzione in un server prima di far scattare la scalabilità verticale (scale up)
  SImin: 2 # numero minimo di job correntemente in esecuzione in un server prima di far scattare la scalabilità verticale (scale down)
  R0max: 3.4 # media del tempo di risposta per job in un server prima di far scattare la scalabilità orizzontale (scale in)
  R0min: 3.0 # media del tempo di risposta per job in un server prima di far scattare la scalabilità orizzontale (scale out)
  slidingWindowSize: 10 # dimensione della finestra mobile per il calcolo della media del tempo di risposta
  initialServerCount: 1 # numero di server iniziali SENZA CONTARE LO SPIKE SERVER
  cpuMultiplierSpike: 2 # moltiplicatore della CPU per il server spike
  cpuPercentageSpike: 0.4 # percentuale di CPU assegnata alla applicazione del server spike
  schedulingPolicy: "least_load"   # valori possibili: least_load, round_robin